### ISSUE TITLE
gitme.js: Failed to clone repo [enonic/doc-xp]

### ISSUE THREAD

**Issue by hjelmevold** [enonic/site-developer#132]
After upgrading the site-developer app to work with 7.0 (see the branch "7.0"), trying to update a documentation content from the preview window results in a stack trace:

```
08:04:27.314 INFO  com.enonic.site.developer - (/services/gitme/gitme.js) Docs and guides referencing repo "https://github.com/enonic/doc-xp" - 1
08:04:28.291 INFO  c.e.s.d.t.repo.GetVersionsCommand - Fetching [/docs/versions.json] from [enonic/doc-xp] ...
08:04:28.381 INFO  c.e.s.d.t.repo.GetVersionsCommand - Fetched [versions.json]
08:04:28.394 INFO  com.enonic.site.developer - (/services/gitme/gitme.js) versions: {"versions":[{"label":"7.0.0","checkout":"master","commitId":"10cc00f79839dca03f984b9acbae60db974bbb16","latest":true}]}
08:04:28.897 INFO  c.e.s.d.tools.repo.CloneRepoCommand - Retrieving Git repository from [ https://github.com/enonic/doc-xp : master ] ...
08:04:28.974 ERROR c.e.s.d.tools.repo.CloneRepoCommand - Failed to clone repo [enonic/doc-xp]
org.eclipse.jgit.api.errors.JGitInternalException: Creating directories for /enonic-xp/bin/./docs-repos/enonic/doc-xp/.CloneRepoTemporaryDirectory/.git failed
	at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:119)
	at org.eclipse.jgit.api.CloneCommand.init(CloneCommand.java:261)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:189)
	at com.enonic.site.developer.tools.repo.CloneRepoCommand.cloneGitRepository(CloneRepoCommand.java:77)
	at com.enonic.site.developer.tools.repo.CloneRepoCommand.doExecute(CloneRepoCommand.java:54)
	at com.enonic.site.developer.tools.repo.CloneRepoCommand.execute(CloneRepoCommand.java:39)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$19401$11004AA$gitme$cu1$restOf.L:1#L:1-12#m(com.enonic.site.developer:/services/gitme/gitme.js:1)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$19399$9454AAA$gitme$cu1$restOf.L:1#L:1-12#d#task#L:1-1#L:1#L:1-1#L:1#L:1#L:1(com.enonic.site.developer:/services/gitme/gitme.js:1)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$19379$9441ADA$gitme.L:1#L:1-12#d#task#L:1-1#L:1#L:1-1#L:1#L:1(com.enonic.site.developer:/services/gitme/gitme.js:1)
	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeArray$9.forEach(Unknown Source)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.arrays.IteratorAction.apply(Unknown Source)
	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeArray.forEach(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$19378$9415AAA$gitme.L:1#L:1-12#d#task#L:1-1#L:1#L:1-1#L:1(com.enonic.site.developer:/services/gitme/gitme.js:1)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$19377$9071A$gitme$cu1$restOf.L:1#L:1-12#d#task#L:1-1#L:1#L:1-1(com.enonic.site.developer:/services/gitme/gitme.js:1)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$19366$8582A$gitme$cu1$restOf.L:1#L:1-12#d#task#L:1-1#L:1(com.enonic.site.developer:/services/gitme/gitme.js:1)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$19321$8565A$gitme.L:1#L:1-12#d#task#L:1-1(com.enonic.site.developer:/services/gitme/gitme.js:1)
	at jdk.nashorn.javaadapters.java_util_concurrent_Callable.call(Unknown Source)
	at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:101)
	at com.enonic.xp.lib.context.ContextHandlerBean.run(ContextHandlerBean.java:36)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$19324$1216AA$context$cu1$restOf.L:1#run(com.enonic.site.developer:/lib/xp/context.js:56)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$19323$8477A$gitme.L:1#L:1-12#d#task#L:1(com.enonic.site.developer:/services/gitme/gitme.js:1)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$19322$8465$gitme$cu1$restOf.L:1#L:1-12#d#task(com.enonic.site.developer:/services/gitme/gitme.js:1)
	at jdk.nashorn.javaadapters.java_util_function_Function.apply(Unknown Source)
	at com.enonic.xp.lib.task.TaskWrapper.runTask(TaskWrapper.java:38)
	at com.enonic.xp.task.TaskProgressReporterContext.lambda$withContext$0(TaskProgressReporterContext.java:36)
	at com.enonic.xp.lib.task.TaskWrapper.run(TaskWrapper.java:31)
	at com.enonic.xp.impl.task.TaskWrapper.lambda$callTaskWithContext$0(TaskWrapper.java:90)
	at com.enonic.xp.context.ContextImpl.callWith(ContextImpl.java:101)
	at com.enonic.xp.impl.task.TaskWrapper.callTaskWithContext(TaskWrapper.java:89)
	at com.enonic.xp.impl.task.TaskWrapper.doRun(TaskWrapper.java:75)
	at com.enonic.xp.trace.Tracer.lambda$trace$0(Tracer.java:42)
	at com.enonic.xp.trace.Tracer.traceEx(Tracer.java:72)
	at com.enonic.xp.trace.Tracer.trace(Tracer.java:51)
	at com.enonic.xp.trace.Tracer.trace(Tracer.java:41)
	at com.enonic.xp.impl.task.TaskWrapper.run(TaskWrapper.java:66)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Creating directories for /enonic-xp/bin/./docs-repos/enonic/doc-xp/.CloneRepoTemporaryDirectory/.git failed
	at org.eclipse.jgit.util.FileUtils.mkdirs(FileUtils.java:371)
	at org.eclipse.jgit.internal.storage.file.FileRepository.create(FileRepository.java:298)
	at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:116)
	... 39 common frames omitted
08:04:28.977 ERROR com.enonic.site.developer - (/services/gitme/gitme.js) java.lang.RuntimeException: Failed to clone repo [enonic/doc-xp]
```

**Comment by hjelmevold** [comment]
When I upgraded this app, there were many places where I had to use lib-context to make sure that contents was created in the "draft" branch. Such as here: https://github.com/enonic/site-developer/blob/7.0/src/main/resources/lib/doc.es#L73

Perhaps there is an error in some of this new code? Hmm.

**Comment by hjelmevold** [comment]
The stack trace in the original issue description is perhaps just a problem in the QA environment. After some conversation with Aliaksandr, it seems that this stack trace could be more relevant:

```
2019-04-11 10:02:58,765 INFO  com.enonic.site.developer - (/services/gitme/gitme.js) Docs and guides referencing repo "https://github.com/enonic/doc-xp" - 1
2019-04-11 10:02:59,706 INFO  c.e.s.d.t.repo.GetVersionsCommand - Fetching [/docs/versions.json] from [enonic/doc-xp] ...
2019-04-11 10:02:59,988 INFO  c.e.s.d.t.repo.GetVersionsCommand - Fetched [versions.json]
2019-04-11 10:02:59,998 INFO  com.enonic.site.developer - (/services/gitme/gitme.js) versions: {"versions":[{"label":"7.0.0","checkout":"master","commitId":"10cc00f79839dca03f984b9acbae60db974bbb16","latest":true}]}
2019-04-11 10:03:00,423 INFO  c.e.s.d.tools.repo.CloneRepoCommand - Retrieving Git repository from [ https://github.com/enonic/doc-xp : master ] ...
2019-04-11 10:03:03,243 INFO  c.e.s.d.tools.repo.CloneRepoCommand - Git repository retrieved.
2019-04-11 10:03:05,330 ERROR c.e.s.d.t.a.BuildAsciiDocCommand - Failed to build asciidoc in [enonic/doc-xp]
org.jruby.exceptions.LoadError: (LoadError) no such file to load -- asciidoctor
    at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:984)
    at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:59)
    at RUBY.<main>(<script>:12)
2019-04-11 10:03:05,331 ERROR com.enonic.site.developer - (/services/gitme/gitme.js) java.lang.RuntimeException: Failed to build asciidoc in [enonic/doc-xp]
```

**Comment by sigdestad** [comment]
Hmm, this May be missing from the upgrade docs. You always have to use context.run now, since params are removed

**Comment by hjelmevold** [comment]
After the latest commit by @ashklianko it now works well to do the documentation import on localhost. The error described in comment number 3 above has been solved.

However, I deployed the latest code to QA, and the error in the original comment is still present. So it's working well on localhost, but not in the QA environment.

**Comment by hjelmevold** [comment]
> Hmm, this May be missing from the upgrade docs. You always have to use context.run now, since params are removed

I did this for all functions that specified a branch in my commit https://github.com/enonic/site-developer/commit/da9b092183e24ef94005b44662abd491c3f46020

Since it works on localhost, I assume that the context.run() code in controllers and libs is working as it should. I cannot rule out that there might be something wrong in my upgraded JavaScript code, but the stack trace is a Java error `java.io.IOException: Creating directories for /enonic-xp/bin/./docs-repos/enonic/doc-xp/.CloneRepoTemporaryDirectory/.git failed` so I think that's a more sensible area to investigate, for now.

**Comment by sigdestad** [comment]
My suggestion is that we use either the /tmp folder to clone and build adoc files, or create a XP_HOME/tmp/ folder - I guess the last one would work for both win and linux without additional work?

**Comment by sigdestad** [comment]
So, this is still failing - and is now fully blocking release of XP7.
We should clone into $XP_HOME/tmp or similar.

Here is from our cluster, still trying to unzip in bin folder:
`17:06:51.340 ERROR c.e.s.d.tools.repo.CloneRepoCommand - Failed to clone repo [enonic/doc-xp]org.eclipse.jgit.api.errors.JGitInternalException: Creating directories for /enonic-xp/bin/./docs-repos/enonic/doc-xp/.CloneRepoTemporaryDirectory/.git failed	at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:119)	at org.eclipse.jgit.api.CloneCommand.init(CloneCommand.java:261)	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:189)	at com.enonic.site.developer.tools.repo.CloneRepoCommand.cloneGitRepository(CloneRepoCommand.java:77)`

**Comment by sigdestad** [comment]
NB! Remember to make changes in 7.0 branch only

**Comment by ashklianko** [comment]
I'll try to  fix today/tomorrow

**Comment by ashklianko** [comment]
Updated 7.0 to use $XP_HOME/tmp.
If problem with creating folders persists then I'll discuss with @diegopasten regarding possible issues on docker that prevend dirs from creating.

**Comment by sigdestad** [comment]
Hurrey! This is now working :-)
